In [21]:
import pandas as pd
import numpy as np

In [22]:
x=pd.Series(['akriti','pihu','ankita','prity'])
type(x)
x.str.startswith("a")
x.str.endswith("a")
len(x)

4

In [23]:
df=pd.read_csv('cars.csv')

In [24]:
type(df)
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [25]:
df['brand'].str.lower()

0        maruti
1         skoda
2         honda
3       hyundai
4        maruti
         ...
8123    hyundai
8124    hyundai
8125     maruti
8126       tata
8127       tata
Name: brand, Length: 8128, dtype: object

In [26]:
x.str.lower()

0    akriti
1      pihu
2    ankita
3     prity
dtype: object

In [28]:
x.str.upper()
x.str.capitalize()

0    Akriti
1      Pihu
2    Ankita
3     Prity
dtype: object

In [29]:
df['brand'].str.strip()

0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: brand, Length: 8128, dtype: object

In [30]:
df['brand'].str.title()

0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: brand, Length: 8128, dtype: object

In [32]:
df['brand'].str.len()
df['brand'].str.len().sum()

np.int64(50259)

In [33]:
[df['brand'].str.len()==50]

[0       False
 1       False
 2       False
 3       False
 4       False
         ...
 8123    False
 8124    False
 8125    False
 8126    False
 8127    False
 Name: brand, Length: 8128, dtype: bool]

In [41]:
# df['brand'][df['brand'].str.len()==50].values[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [47]:
df['brand'][df['brand'].str.len()==50]

Series([], Name: brand, dtype: object)

In [52]:
# df['owner'][df['owner'].str.split('')]
# df['owner'].str.split('')

0                   [, F, i, r, s, t,  , O, w, n, e, r, ]
1                [, S, e, c, o, n, d,  , O, w, n, e, r, ]
2                   [, T, h, i, r, d,  , O, w, n, e, r, ]
3                   [, F, i, r, s, t,  , O, w, n, e, r, ]
4                   [, F, i, r, s, t,  , O, w, n, e, r, ]
                              ...
8123                [, F, i, r, s, t,  , O, w, n, e, r, ]
8124    [, F, o, u, r, t, h,  , &,  , A, b, o, v, e,  ...
8125                [, F, i, r, s, t,  , O, w, n, e, r, ]
8126                [, F, i, r, s, t,  , O, w, n, e, r, ]
8127                [, F, i, r, s, t,  , O, w, n, e, r, ]
Name: owner, Length: 8128, dtype: object

In [80]:
df=pd.read_csv('data_science_job.csv')

In [81]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0.0

In [82]:
df['enrolled_university'].str.split('_')

0          [no, enrollment]
1          [no, enrollment]
2        [Full time course]
3                       NaN
4          [no, enrollment]
                ...
19153      [no, enrollment]
19154      [no, enrollment]
19155      [no, enrollment]
19156      [no, enrollment]
19157      [no, enrollment]
Name: enrolled_university, Length: 19158, dtype: object

In [83]:
df['enrolled_university'].str.get(0)

0          n
1          n
2          F
3        NaN
4          n
        ...
19153      n
19154      n
19155      n
19156      n
19157      n
Name: enrolled_university, Length: 19158, dtype: object

In [84]:
df['enrolled_university'].str.split('_').get(0)

['no', 'enrollment']

In [85]:
df['enrolled_university'].str.split('_').str.get(0)

0                      no
1                      no
2        Full time course
3                     NaN
4                      no
               ...
19153                  no
19154                  no
19155                  no
19156                  no
19157                  no
Name: enrolled_university, Length: 19158, dtype: object

In [88]:
df['company_size'].str.split('-',expand=True)
df['company_size'].str.split('-',n=2,expand=True)
df[['a','b']]=df['company_size'].str.split('-',expand=True)

In [89]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target,a,b
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0,NaN,NaN
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0,50,99
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0,NaN,NaN
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0,NaN,NaN
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0,50,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1.0,NaN,NaN
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1.0,NaN,NaN
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0.0,50,99
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0.0,500,999
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0.0,NaN,NaN

In [90]:
df['a'].value_counts()

a
50        3083
100       2571
10000+    2019
10/49     1471
1000      1328
<10       1308
500        877
5000       563
Name: count, dtype: int64

In [95]:
df['a']=df['a'].str.replace('50','40')

In [96]:
df['a'].value_counts()

a
40        3083
100       2571
10000+    2019
10/49     1471
1000      1328
<10       1308
400        877
4000       563
Name: count, dtype: int64

In [100]:
df['relevent_experience'][df['relevent_experience'].str.startswith('No')]

1        No relevent experience
2        No relevent experience
3        No relevent experience
10       No relevent experience
13       No relevent experience
                  ...
19145    No relevent experience
19147    No relevent experience
19151    No relevent experience
19153    No relevent experience
19157    No relevent experience
Name: relevent_experience, Length: 5366, dtype: object

In [101]:
df[df['relevent_experience'].str.startswith('No')]

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target,a,b
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0,40,99
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0,NaN,NaN
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0,NaN,NaN
10,29452,city_21,0.624,NaN,No relevent experience,Full time course,High School,NaN,2.0,NaN,NaN,32.0,1.0,NaN,NaN
13,5826,city_21,0.624,Male,No relevent experience,NaN,NaN,NaN,2.0,NaN,NaN,24.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19145,155,city_44,0.725,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,Pvt Ltd,190.0,0.0,NaN,NaN
19147,21319,city_21,0.624,Male,No relevent experience,Full time course,Graduate,STEM,1.0,100-500,Pvt Ltd,52.0,1.0,100,500
19151,11385,city_149,0.689,Male,No relevent experience,Full time course,Graduate,NaN,2.0,NaN,NaN,60.0,0.0,NaN,NaN
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1.0,NaN,NaN
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0.0,NaN,NaN

In [103]:
df[df['city'].str.isdigit()]

Empty DataFrame
Columns: [enrollee_id, city, city_development_index, gender, relevent_experience, enrolled_university, education_level, major_discipline, experience, company_size, company_type, training_hours, target, a, b]
Index: []

In [106]:
# df[df['experience'].str.isdigit()]
df['experience'].str.isdigit()
df['a'].str.isdigit()

AttributeError: Can only use .str accessor with string values!

In [109]:
df['gender'].str.contains('male',case=False)

0        True
1        True
2         NaN
3         NaN
4        True
         ...
19153    True
19154    True
19155    True
19156    True
19157     NaN
Name: gender, Length: 19158, dtype: object

In [112]:
df['gender'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$]')

0        False
1        False
2          NaN
3          NaN
4        False
         ...
19153    False
19154    False
19155    False
19156    False
19157      NaN
Name: gender, Length: 19158, dtype: object

In [116]:
df['city'].str[:]
df['city'].str[:1]

0        c
1        c
2        c
3        c
4        c
        ..
19153    c
19154    c
19155    c
19156    c
19157    c
Name: city, Length: 19158, dtype: object

In [118]:
df['city'].str[::-1]

0        301_ytic
1         04_ytic
2         12_ytic
3        511_ytic
4        261_ytic
           ...
19153    371_ytic
19154    301_ytic
19155    301_ytic
19156     56_ytic
19157     76_ytic
Name: city, Length: 19158, dtype: object

In [121]:
df['city'].str[::2]

0        ct_0
1        ct_0
2        ct_1
3        ct_1
4        ct_6
         ...
19153    ct_7
19154    ct_0
19155    ct_0
19156    ct_5
19157    ct_7
Name: city, Length: 19158, dtype: object

In [122]:
df.str[::2]

AttributeError: 'DataFrame' object has no attribute 'str'